brace_style="SameLineWhere"
control_brace_style="AlwaysSameLine"
error_on_line_overflow=true
fn_params_layout="Tall"
format_code_in_doc_comments=true
group_imports="StdExternalCrate"
hard_tabs=false
imports_granularity="Module"
indent_style="Block"
max_width=100
merge_derives=true
newline_style="Unix"
normalize_comments=true
remove_nested_parens=true
reorder_impl_items=true
reorder_imports=true
reorder_modules=true
space_after_colon=true
space_before_colon=false
spaces_around_ranges=false
tab_spaces=4
trailing_comma="Vertical"
unstable_features=true
use_field_init_shorthand=true
# https://rust-lang.github.io/rustfmt/#use_small_heuristics
use_small_heuristics="Default"
where_single_line=true
wrap_comments=true
